all: mod51 filtra1a10 maxmin
mod51: mod51.c dbg.h
	gcc -o mod51 mod51.c
filtra1a10: filtra1a10.c dbg.h
	gcc -o filtra1a10 filtra1a10.c
maxmin: maxmin.c dbg.h
	gcc -o maxmin maxmin.c
clean:
	rm mod51 filtra1a10 maxmin
